# Generated by Django 3.2.25 on 2024-12-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='project_turnaround',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
